// import { autoGenerateData, IUser } from "../../seed/data";
// import { DataTypes } from "../../seed/dataTypes";
import { UsersState, UserReduxActionTypes, UserReduxActions } from "./types";
import { reduxSwitchcase } from "../../core/utils/validation-helpers";
import { IUser } from "../../core/types/data-type-definitions";

const defaultUsersState: UsersState = {
	// users: autoGenerateData(DataTypes.User, 10)
	users: []
}

type UsersCaseMap = {
	[key in UserReduxActionTypes]: UsersState;
}

function userCases(state: UsersState, action: UserReduxActions) {
	const cases: UsersCaseMap = {
		[UserReduxActionTypes.CREATE_USER]: Object.assign({}, state, { users: [ ...state.users, action.payload as IUser ] }),
	}
	return cases;
}

export function userReducer(
	state: UsersState = defaultUsersState,
	action: UserReduxActions
): UsersState {
	return reduxSwitchcase(userCases(state, action))(state)(action.type);
}
