/**
 * Depricated
 */

import React, { Component } from 'react';

import FlexibleItemsListView from '../FlexibleItemsList/FlexibleItemsList';
// import { IProject, IDataType, autoGenerateData } from '../../seed/data';
import FlexibleItemDetailView from '../FlexibleItemDetail/FlexibleItemDetailView';
import { IDataType } from '../../core/utils/mock-data-gen-schemas';
import { IProject, DataTypes } from '../../core/types/data-type-definitions';
import { autoGenerateMockData } from '../../core/utils/generate-mock-data';
// import { DataTypes } from '../../seed/dataTypes';

interface IProjectsListPage {
	dataType: IDataType;
}

export default class ProjectsListPage extends Component<IProjectsListPage, {}> {
	render() {
		const projects: IProject[] = autoGenerateMockData(DataTypes.Project, 10);
		return (
			<div style={styles.container} className="page-container">
				<h3 className="page-container__title">Projects List Page</h3>
				<div style={styles.bottom}>
					<div style={styles.left}>
						<FlexibleItemsListView<IProject> items={projects} dataType={this.props.dataType} type={DataTypes.Project} />
					</div>
					<div style={styles.right}>
						<FlexibleItemDetailView<IProject> item={projects[0]} type={DataTypes.Project} />
					</div>
				</div>
			</div>
		);
	}
}

const styles = {
	left: {
		flex: 1,
	},
	right: {
		flex: 1,
	},
	container: {
		display: 'flex',
		flexFlow: 'column',
	},
	bottom: {
		display: 'flex'
	},
};
